# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  file-to-run:  # id of input
    description: 'Action file to run as test'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  file_run_status: # id of output
    description: 'The results of the file we ran'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet, inputs.file-to-run }}
